### ISSUE TITLE
Good bot, but...

### ISSUE THREAD

**Issue by chrma-coder** [johncorderox/Attendance-Discord-Bot#1]
I'm not sure how this can be deployed to Heroku, as I don't see a button that says it can be deployed to Heroku.  I like the idea of your bot, as you have a roster for a list of the members for a team in the guild, however, your about doesn't explain much about how to deploy the code onto Heroku.  If it could be more briefly explained, that would be great.

**Comment by johncorderox** [comment]
@chrma-coder 

Hey,
This project is pretty much dead and I stopped using discord before I could start learning more about the deployment. Sorry about that. If you ever figure something out, feel free to use this at your own accord but i forgot how this project worked! lol

**Comment by chrma-coder** [comment]
Lol.  Alrighty, I'll see what I can do. :)
